// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'buttonContainer': string;
  'emptyStateCard': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
